services:
  # Основная база данных для Situs Service
  postgres:
    image: postgres:15
    container_name: situs-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-situs}
      POSTGRES_USER: ${POSTGRES_USER:-situs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-situs_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '55432:5432'
    networks:
      - situs-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-situs} -d ${POSTGRES_DB:-situs}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  # Тестовая база данных
  postgres-test:
    image: postgres:15
    container_name: situs-postgres-test
    restart: always
    profiles:
      - test
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-situs_test}
      POSTGRES_USER: ${POSTGRES_USER:-situs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-situs_password}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - situs-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-situs} -d ${POSTGRES_DB:-situs_test}']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кэширования и сессий
  redis:
    image: redis:7
    container_name: situs-redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - situs-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  # Situs Service - основной сервис
  situs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: situs-api
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-situs}:${POSTGRES_PASSWORD:-situs_password}@postgres:5432/${POSTGRES_DB:-situs}?schema=public
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET:-change_me_at_least_32_chars_long}
      - JWT_ACCESS_EXPIRES_IN=30m
      - JWT_REFRESH_EXPIRES_IN=7d
      - VITE_ENV=production
    volumes:
      - ./prisma:/app/prisma
    networks:
      - situs-network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3002/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      - postgres

  # Prisma Studio для управления базой данных
  prisma-studio:
    image: node:18-alpine
    container_name: situs-prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5555:5555'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-situs}:${POSTGRES_PASSWORD:-situs_password}@postgres:5432/${POSTGRES_DB:-situs}?schema=public
    depends_on:
      - postgres
    networks:
      - situs-network
    command: ['npx', 'prisma', 'studio', '--hostname', '0.0.0.0', '--port', '5555']

  situs-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: situs-web
    ports:
      - '5178:80'
    depends_on:
      - situs-api
    networks:
      - situs-network

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:

networks:
  situs-network:
    driver: bridge
